Configured CI
mpark/slb pull request #6
Opened 2017-11-29 14:31 UTC by K-ballo

Configured Travis and Appveyor.

2017-11-30 17:17 UTC, mpark requested changes

2017-11-30 17:17 UTC, mpark commented on .travis.yml
> +            - george-edison55-precise-backports
Is this a `precise` specific thing...? I'm not sure what it's for exactly, but
we should be on `trusty` by default now: https://blog.travis-ci.com/2017-08-31-trusty-as-default-status

2017-11-30 17:17 UTC, mpark commented on .travis.yml
> +    # gcc-4.8
MPark.Variant currently doesn't support GCC 4.8.
At least at the time, I decided it wasn't worth the effort.
Do you think it's worth the effort to support 4.8?

2017-11-30 17:17 UTC, mpark commented on .travis.yml
> +    - env: GCC_VERSION=4.9 CXXFLAGS="-std=c++1y"
GCC 4.9 supports `-std=c++14`.

2017-11-30 17:17 UTC, mpark commented on .travis.yml
> +            - cmake
Hm, the 4.8/4.9 matrices above didn't include `cmake` nor `cmake-data`...
Are these required here and below for some reason not applicable to the 4.8/4.9 matrices?

__UPDATE__: Looking at the Travis logs, it looks like this is unnecessary.
```
cmake is already the newest version (3.2.2-2~ubuntu14.04.1~ppa1).
cmake-data is already the newest version (3.2.2-2~ubuntu14.04.1~ppa1).
```

2017-11-30 17:17 UTC, mpark commented on .travis.yml
> +    - env: GCC_VERSION=7 CXXFLAGS="-std=c++1z"
GCC 7 suports `-std=c++17`.

2017-11-30 17:17 UTC, mpark commented on .travis.yml
> +            - llvm-toolchain-precise-3.9
We can do `llvm-toolchain-trusty-3.9` here.

2017-11-30 17:17 UTC, mpark commented on .travis.yml
> +      dist: trusty
We should be on `trusty` by default now: https://blog.travis-ci.com/2017-08-31-trusty-as-default-status

2017-11-30 17:17 UTC, mpark commented on .travis.yml
> +  - export CXXFLAGS="${CXXFLAGS} -Wall -Wextra -Werror"
Do we also want `-pedantic`?

2017-11-30 18:22 UTC, K-ballo commented on .travis.yml
> +    # gcc-4.8
I do, to the extent that it is reasonable. I'm ready to take responsibility for it.

2017-11-30 18:23 UTC, K-ballo commented on .travis.yml
> +            - george-edison55-precise-backports
I'll try taking these out, it'd be nice if things just work nowadays

2017-11-30 18:24 UTC, K-ballo commented on .travis.yml
> +  - export CXXFLAGS="${CXXFLAGS} -Wall -Wextra -Werror"
We definitively do!

2017-11-30 19:09 UTC, mpark commented on .travis.yml
> +# Distributed under the Boost Software License, Version 1.0. (See accompanying
Let's do:
```
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)
```

2017-11-30 19:09 UTC, mpark commented on .appveyor.yml
> +# Distributed under the Boost Software License, Version 1.0. (See accompanying
Let's do:
```
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)
```

2017-12-01 01:06 UTC, mpark approved these changes

2017-12-01 14:05 UTC, merged